### ISSUE TITLE
Testing the module

### ISSUE THREAD

**Issue by SxMShaDoW** [5punk/react-slack-chat#4]
How do we unit test the module?

When we submit PRs:
Is there a travisCI build or appvoyer? 
Is there a lint/style check?
Is there any static code analysis and or codecov?

**Comment by 5punk** [comment]
None exist as of now.
Feel free to submit a PR.

As for the lint / styles, adhere to the styles inside the [.eslintrc](https://github.com/5punk/react-slack-chat/blob/master/.eslintrc)

**Comment by SxMShaDoW** [comment]
Can we keep this open until it is there?

You can sign up for free services like travisCI and codeCov that I wouldn't be able to contribute.

**Comment by SxMShaDoW** [comment]
travisCI ftw!

https://codecov.io takes a few seconds to sign up and creates a .yml file in the repo. 

minimum/simple .yml:

```
comment:
  layout: header, changes, diff
coverage:
  status: {}
```


more detailed example: 

```

codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

    hipchat:
      default:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null

    gitter:
      default:
        url: null
        threshold: null
        branches: null
        message: null

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null

    irc:
      default:
        server: null
        channel: null
        branches: null
        threshold: null
        message: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
```

What it does for PRs:
![image](https://cloud.githubusercontent.com/assets/9122189/20861877/cb4bce60-b94f-11e6-8714-38458ca663d8.png)
